name: Release binaries

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [linux, windows]
        goarch: [amd64]
    steps:
      - uses: bigbird023/github-actions/.github/workflows/go-release-publishToGithub-workflow.yaml@main
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}